#include "dictator_Native.h"
#include "webrtc/webrtc/common_audio/vad/include/webrtc_vad.h"
#include "jni_util.h"

JNIEXPORT jlong JNICALL Java_dictator_Native_createVAD(JNIEnv *env, jclass clazz, jint aggressiveness) {
    VadInst *handle = WebRtcVad_Create();
    if (handle == NULL) {
        THROW_EXC(env, RUNTIME_EXC_CLASS, "Couldn't create VAD instance");
        goto err;
    }
    if (WebRtcVad_Init(handle) != 0) {
        THROW_EXC(env, RUNTIME_EXC_CLASS, "Couldn't initialize VAD instance");
        goto err;
    }
    if (WebRtcVad_set_mode(handle, aggressiveness) != 0) {
        THROW_EXC(env, RUNTIME_EXC_CLASS, "Couldn't set VAD aggressiveness");
        goto err;
    }
    return (jlong) handle;
    err:
        if (handle != NULL) {
            WebRtcVad_Free(handle);
        }
        return (jlong) NULL;
}

JNIEXPORT void JNICALL Java_dictator_Native_freeVAD(JNIEnv *env, jclass clazz, jlong handle) {
    WebRtcVad_Free((VadInst*) handle);
}

JNIEXPORT jboolean JNICALL Java_dictator_Native_processVAD(JNIEnv *env, jclass clazz, jlong handle,
                                                           jint sampleRate, jbyteArray audio) {
    size_t frameLen = (*env)->GetArrayLength(env, audio) / 2;
    // TODO typecast vs memcpy
    int16_t *audioBytes = (*env)->GetPrimitiveArrayCritical(env, audio, NULL);
    if (audioBytes == NULL) {
        // OOM is generated by GetPrimitiveArrayCritical
        return JNI_FALSE;
    }
    int result = WebRtcVad_Process((VadInst*) handle, sampleRate, audioBytes, frameLen);
    (*env)->ReleasePrimitiveArrayCritical(env, audio, audioBytes, JNI_ABORT);

    if (result == -1) {
        THROW_EXC(env, RUNTIME_EXC_CLASS, "Couldn't process audio");
        return JNI_FALSE;
    }
    return result == 1 ? JNI_TRUE : JNI_FALSE;
}
