/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dictator_Native */

#ifndef _Included_dictator_Native
#define _Included_dictator_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dictator_Native
 * Method:    createVAD
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dictator_Native_createVAD
  (JNIEnv *, jclass, jint);

/*
 * Class:     dictator_Native
 * Method:    freeVAD
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dictator_Native_freeVAD
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
