/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dictator_Native */

#ifndef _Included_dictator_Native
#define _Included_dictator_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dictator_Native
 * Method:    findElement
 * Signature: (Ljava/awt/Window;II)Ldictator/Native/UIElem;
 */
JNIEXPORT jobject JNICALL Java_dictator_Native_findElement
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     dictator_Native
 * Method:    createVAD
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dictator_Native_createVAD
  (JNIEnv *, jclass, jint);

/*
 * Class:     dictator_Native
 * Method:    freeVAD
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dictator_Native_freeVAD
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dictator_Native
 * Method:    processVAD
 * Signature: (JI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_dictator_Native_processVAD
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     dictator_Native
 * Method:    createLAME
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_dictator_Native_createLAME
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     dictator_Native
 * Method:    encodeLAME
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dictator_Native_encodeLAME
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     dictator_Native
 * Method:    freeLAME
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dictator_Native_freeLAME
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dictator_Native
 * Method:    freeElement
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dictator_Native_freeElement
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
